# Generated by Django 5.1.1 on 2024-10-31 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='selected_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access_module.restaurant_chain_branch'),
        ),
    ]
