# Generated by Django 5.1.1 on 2024-10-31 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_module', '0002_custom_user_selected_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant_chain_branch',
            name='image',
            field=models.ImageField(null=True, upload_to='restaurant_chain/branches/'),
        ),
    ]
