# Generated by Django 5.1.1 on 2024-10-31 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_module', '0003_restaurant_chain_branch_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant_chain_branch',
            name='image',
            field=models.ImageField(null=True, upload_to='restaurant_chain/branch_images/'),
        ),
    ]
