# Generated by Django 5.0.7 on 2024-08-30 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shopping_Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cart_Product_Shopping_Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cart_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_module.cart_product')),
                ('id_shopping_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_module.shopping_cart')),
            ],
        ),
        migrations.CreateModel(
            name='Published_Product_Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_module.publication')),
                ('id_published_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_module.published_product')),
            ],
            options={
                'unique_together': {('id_published_product', 'id_publication')},
            },
        ),
        migrations.AddField(
            model_name='cart_product',
            name='id_published_product_publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_module.published_product_publication'),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=20)),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('id_cart_product_shopping_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_module.cart_product_shopping_cart')),
            ],
        ),
    ]
