# Generated by Django 5.1.1 on 2024-10-08 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_module', '0004_alter_product_inventory_total_quantity'),
        ('sales_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=20)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('total_price', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='cart_product_shopping_cart',
            name='id_cart_product',
        ),
        migrations.RemoveField(
            model_name='cart_product_shopping_cart',
            name='id_shopping_cart',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='id_cart_product_shopping_cart',
        ),
        migrations.RemoveField(
            model_name='cart_product',
            name='cart_quantity',
        ),
        migrations.RemoveField(
            model_name='cart_product',
            name='id_published_product_publication',
        ),
        migrations.AddField(
            model_name='cart_product',
            name='cart_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_module.published_product'),
        ),
        migrations.AddField(
            model_name='cart_product',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cart_product',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sales_module.order'),
        ),
        migrations.DeleteModel(
            name='Shopping_Cart',
        ),
        migrations.DeleteModel(
            name='Cart_Product_Shopping_Cart',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
