# Generated by Django 5.1.1 on 2024-11-13 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_module', '0002_remove_cart_product_shopping_cart_id_cart_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_product',
            name='category',
            field=models.CharField(default='None', max_length=60),
        ),
    ]
