# Generated by Django 5.1.1 on 2024-10-09 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_module', '0001_initial'),
        ('sales_module', '0002_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='access_module.foundation'),
        ),
    ]
