# Generated by Django 5.1.1 on 2024-10-17 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_module', '0004_remove_cart_product_cart_product_cart_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_product',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='inventory/image/'),
        ),
    ]
