# Generated by Django 5.0.7 on 2024-08-30 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('category', models.CharField(max_length=60)),
                ('sale_price', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='inventory/image/')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity', models.PositiveIntegerField()),
                ('id_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_module.inventory')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_module.product')),
            ],
            options={
                'unique_together': {('id_product', 'id_inventory')},
            },
        ),
        migrations.CreateModel(
            name='Published_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_type', models.CharField(max_length=20)),
                ('publish_quantity', models.PositiveIntegerField()),
                ('publish_price', models.PositiveIntegerField()),
                ('pick_up_time', models.TimeField()),
                ('id_product_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_module.product_inventory')),
            ],
        ),
    ]
