# Generated by Django 5.0.7 on 2024-09-03 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_module', '0002_alter_inventory_creation_date'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('creation_date',), name='unique_creation_date'),
        ),
    ]
