# Generated by Django 5.1.1 on 2024-09-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_module', '0003_inventory_unique_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_inventory',
            name='total_quantity',
            field=models.IntegerField(),
        ),
    ]
