# Generated by Django 5.1.1 on 2024-11-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_module', '0005_published_product_pick_up_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='published_product',
            name='place',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
