# Generated by Django 5.1.1 on 2024-11-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_module', '0006_published_product_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_inventory',
            name='pick_up_address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
