# Generated by Django 5.1.1 on 2024-11-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_module', '0007_product_inventory_pick_up_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_inventory',
            name='pick_up_address',
            field=models.CharField(default='none', max_length=200, null=True),
        ),
    ]
