# Generated by Django 5.1.1 on 2024-11-11 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_module', '0009_product_pick_up_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_inventory',
            name='pick_up_address',
        ),
        migrations.RemoveField(
            model_name='published_product',
            name='pick_up_address',
        ),
        migrations.RemoveField(
            model_name='published_product',
            name='place',
        ),
        migrations.AddField(
            model_name='product',
            name='place',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
