# Generated by Django 5.1.1 on 2024-11-13 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_module', '0010_remove_product_inventory_pick_up_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wasted_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wasted_quantity', models.PositiveIntegerField()),
                ('wasted_date', models.DateField(auto_now_add=True)),
                ('id_product_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_module.product_inventory')),
            ],
        ),
    ]
